name: Fetch Daily Connections Puzzle

on:
  # Runs every day at 5:00 AM UTC (around midnight in the US)
  schedule:
    - cron: '0 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install the 'requests' library that our script needs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run our Python script with diagnostic commands
      - name: Run fetch script and debug
        run: |
          echo "--- Running python script... ---"
          python fetch_puzzle.py
          echo "--- Python script finished. ---"
          echo "--- Listing files in the directory: ---"
          ls -l

      # Step 5: Commit the new puzzle.json file back to the repository
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Updated daily puzzle"
          file_pattern: puzzle.json
